"""Orthogonal Conversation Modes."""

from enum import Enum


class ConversationMode(str, Enum):
    ASK = "ASK"
    SEARCH = "SEARCH"
    SUMMARIZED = "SUMMARIZED"
    COMPARE = "COMPARE"
    EXPLAIN = "EXPLAIN"
    REVIEW = "REVIEW"
    EXECUTIVE_BRIEF = "EXECUTIVE_BRIEF"
    TECHNICAL_DEEP_DIVE = "TECHNICAL_DEEP_DIVE"
    RISK_REVIEW = "RISK_REVIEW"
    ARCHITECTURE_REVIEW = "ARCHITECTURE_REVIEW"
    COMPLIANCE_AUDIT = "COMPLIANCE_AUDIT"
    BRAINSTORM = "BRAINSTORM"
