"""Real test for the 'Why This Answer?' explanation — pins down the 2026-08-20 fix.

Regression pin: ExplanationEngine.generate_explanation() used to be a hardcoded stub
(confidence_score always 0.984, grounding_status always "VERIFIED_GROUNDED",
evidence_used always a fake single entry) with zero live callers. This proves the real
version, wired into process_turn(), reflects what actually happened this turn — real
evidence when company data was retrieved, and an honest "no company data" status when
it wasn't, using the real conversation pipeline end-to-end.
"""
import uuid
import pytest
from sqlalchemy import text
from app.db.database import async_session_factory
from app.processors.ingestion_pipeline import chunk_embed_and_store
from app.conversation.services.conversation_service import ConversationService
from app.conversation.domain.persona import PersonaType
from app.conversation.domain.modes import ConversationMode


async def _make_tenant(name: str) -> str:
    tenant_id = str(uuid.uuid4())
    async with async_session_factory() as session:
        await session.execute(
            text("INSERT INTO tenants (id, name, domain) VALUES (:id, :n, :d)"),
            {"id": tenant_id, "n": name, "d": f"{name.lower().replace(' ', '-')}-{tenant_id[:8]}.company.com"},
        )
        await session.commit()
    return tenant_id


@pytest.mark.asyncio
async def test_explanation_reflects_real_grounded_answer_not_a_fixed_template():
    tenant_id = await _make_tenant("Explanation Test Grounded")
    doc_id = str(uuid.uuid4())
    content = "Runbook: to rotate the API signing key, run `keyctl rotate --service checkout` and notify #platform-eng."
    async with async_session_factory() as session:
        await session.execute(text("SELECT set_config('app.current_tenant_id', :t, true)"), {"t": tenant_id})
        await session.execute(
            text("""
                INSERT INTO documents (id, tenant_id, source_app, resource_category, resource_type,
                    external_id, title, content, s3_bucket, s3_key, is_compressed, file_size_bytes)
                VALUES (:id, :t, 'upload', 'doc', 'file', 'ext1', 'Key Rotation Runbook', :content, 'b', 'k', TRUE, :sz)
            """),
            {"id": doc_id, "t": tenant_id, "content": content, "sz": len(content)},
        )
        await session.commit()
    result = await chunk_embed_and_store(tenant_id=tenant_id, document_id=doc_id, full_text=content, resource_category="doc")
    assert result["status"] == "completed"

    service = ConversationService()
    # Deliberately avoids any word in _BUILTIN_KNOWLEDGE (e.g. "api") — those legitimately
    # short-circuit before the real RAG/explanation pipeline runs, which is correct,
    # pre-existing, untouched-today behavior, not something this test should fight.
    res = await service.process_turn(
        tenant_id=tenant_id, user_id="test_user", session_id=None,
        user_query="how do I rotate the signing key for the checkout service",
        persona=PersonaType.ENGINEER, mode=ConversationMode.ASK,
    )

    assert "explanation" in res, "Every real turn must carry a real explanation, not omit the field."
    exp = res["explanation"]
    assert exp["grounding_status"] != "VERIFIED_GROUNDED" or len(exp["evidence_used"]) > 0, (
        "A 'grounded' status must be backed by real evidence, not asserted regardless of retrieval."
    )
    # The old stub always said "doc_001" / "KnowledgeContext v1" — must never appear now.
    evidence_titles = [e.get("doc_title", "") for e in exp["evidence_used"]]
    assert "doc_001" not in evidence_titles
    assert exp["confidence_score"] != 0.984, "Must not be the old hardcoded stub value."
    assert "confidence_score" in res and res["confidence_score"] >= 0, "Top-level confidence_score (badge) must be real, not always 0."


@pytest.mark.asyncio
async def test_explanation_is_honest_when_nothing_relevant_was_retrieved():
    tenant_id = await _make_tenant("Explanation Test Ungrounded")
    service = ConversationService()
    res = await service.process_turn(
        tenant_id=tenant_id, user_id="test_user", session_id=None,
        user_query="what is the capital of France",
        persona=PersonaType.ENGINEER, mode=ConversationMode.ASK,
    )
    assert "explanation" in res
    exp = res["explanation"]
    # No documents exist for this fresh tenant, so this must NOT falsely claim grounding.
    assert exp["grounding_status"] in ("NO_COMPANY_DATA_RETRIEVED", "NOT_GROUNDED")
    assert exp["reasoning_summary"] != (
        "The response was generated by retrieving grounded knowledge context v1 [1]. "
        "Fact claims were evaluated against enterprise documentation and passed zero-hallucination verification."
    ), "Must not be the old fixed template sentence."
